import React, { useEffect, useState } from "react";
import { useParams } from "react-router-dom";
import { ethers } from "ethers";
import { CONTRACT_ABI, CONTRACT_ADDRESS } from "../contractconfig";
import jsPDF from "jspdf";

const ContractAgreementPage = () => {
  const { id } = useParams();
  const [contractData, setContractData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  useEffect(() => {
    const loadContract = async () => {
      try {
        if (!window.ethereum) throw new Error("MetaMask not detected");

        const provider = new ethers.BrowserProvider(window.ethereum);
        const contract = new ethers.Contract(CONTRACT_ADDRESS, CONTRACT_ABI, provider);

        const data = await contract.getContract(Number(id));

        const formatted = {
          id: Number(id),
          orderId: data.orderId,
          cropName: data.cropName,
          price: ethers.formatUnits(data.price.toString(), "wei"),
          acres: data.acres.toString(),
          deliveryDate: data.deliveryDate,
          status: ["Created", "Accepted", "In Progress", "Completed", "Cancelled"][Number(data.status)],
          farmerWallet: data.farmerWallet,
          buyerWallet: data.buyerWallet,
        };

        setContractData(formatted);
      } catch (err) {
        console.error(err);
        setError("Failed to load contract details");
      } finally {
        setLoading(false);
      }
    };

    loadContract();
  }, [id]);

  const downloadPDF = () => {
  if (!contractData) return;

  const doc = new jsPDF();

  // 🟢 HEADER
  doc.setFillColor(34, 139, 34); // Green Header
  doc.rect(0, 0, 210, 25, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(16);
  doc.text(" FarmaFriend Smart Farming Agreement", 14, 16);

  // 🟢 RESET TEXT COLOR
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(12);

  let y = 35;

  // SECTION TITLE
  doc.setFont("helvetica", "bold");
  doc.text("Contract Overview", 14, y);
  doc.setFont("helvetica", "normal");
  y += 8;

  // Contract summary section
  const details = [
    `Contract ID: ${contractData.orderId}`,
    
    `Status: ${contractData.status}`,
    "",
    `Farmer Wallet: ${contractData.farmerWallet}`,
    `Buyer Wallet: ${contractData.buyerWallet}`,
    "",
    `Crop: ${contractData.cropName}`,
    `Land Area: ${contractData.acres} acres`,
    `Delivery Date: ${contractData.deliveryDate}`,
    `Agreed Price in Rupees:  ${contractData.price}`,
  ];

  details.forEach(line => {
    doc.text(line, 20, y);
    y += 8;
  });

  // Divider line
  doc.setDrawColor(100, 100, 100);
  doc.line(14, y, 196, y);
  y += 10;

  // RESPONSIBILITIES
  doc.setFont("helvetica", "bold");
  doc.text("Responsibilities", 14, y);
  y += 8;
  doc.setFont("helvetica", "normal");
  const duties = [
    "- Farmer ensures proper cultivation, harvest, and timely delivery.",
    "- Buyer agrees to make payment upon satisfactory delivery.",
    "- Both parties must maintain communication for any delays or issues.",
  ];
  duties.forEach(line => {
    doc.text(line, 20, y);
    y += 8;
  });

  // Divider line
  y += 5;
  doc.line(14, y, 196, y);
  y += 10;

  // CURRENT STATUS
  doc.setFont("helvetica", "bold");
  doc.text("Current Blockchain Status:", 14, y);
  doc.setFont("helvetica", "normal");
  y += 8;
  doc.text(`This contract is currently marked as "${contractData.status}".`, 20, y);
  y += 10;

  // AGREEMENT NOTE
  doc.setFont("helvetica", "bold");
  doc.text("Blockchain Record", 14, y);
  doc.setFont("helvetica", "normal");
  y += 8;
  doc.text(
    "This agreement is permanently recorded on the blockchain network, ensuring transparency,",
    20,
    y
  );
  y += 6;
  doc.text(
    "immutability, and security. No modifications can be made after finalization by both parties.",
    20,
    y
  );
  y += 15;

  // SIGNATURE SECTION
  doc.setFont("helvetica", "bold");
  doc.text("Digitally Signed By:", 14, y);
  y += 8;
  doc.setFont("helvetica", "normal");
  doc.text(`Farmer: ${contractData.farmerWallet}`, 20, y);
  y += 8;
  doc.text(`Buyer: ${contractData.buyerWallet}`, 20, y);

  // FOOTER
  y += 20;
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text("Generated by FarmaFriend • Smart Contract Agreement", 14, y);

  // SAVE
  doc.save(`FarmaFriend_Agreement_${contractData.orderId}.pdf`);
};

  if (loading) return <p className="text-center mt-10">Loading contract details...</p>;
  if (error) return <p className="text-center mt-10 text-red-600">{error}</p>;
  if (!contractData) return null;

  return (
    <div className="min-h-screen bg-green-50">
      <nav className="bg-green-700 text-white px-6 py-4">
        <h1 className="text-xl font-bold">FarmaFriend Contract Agreement</h1>
      </nav>

      <div className="max-w-4xl mx-auto py-10 px-6 bg-white rounded-xl shadow-lg mt-8">
        <h2 className="text-2xl font-bold text-green-700 mb-6 text-center">
          Smart Farming Agreement Letter
        </h2>

        <p><strong>Date:</strong> {new Date().toLocaleDateString()}</p>
        <p><strong>Agreement ID:</strong> {contractData.orderId}</p>
        <p><strong>Blockchain Contract ID:</strong> {contractData.id}</p>
        <hr className="my-4" />

        <p className="text-gray-800 leading-relaxed">
          This agreement is made between <strong>Farmer ({contractData.farmerWallet})</strong> and{" "}
          <strong>Buyer ({contractData.buyerWallet})</strong> under the FarmaFriend Smart Farming
          Platform. Both parties agree to the following:
        </p>

        <ul className="list-disc ml-8 my-4 text-gray-700 space-y-1">
          <li>Crop: {contractData.cropName}</li>
          <li>Land Area: {contractData.acres} acres</li>
          <li>Delivery Date: {contractData.deliveryDate}</li>
          <li>Agreed Price: ₹{contractData.price}</li>
        </ul>

        <p className="text-gray-800 leading-relaxed">
          The contract will go through the following states: Created, Accepted, In Progress, Completed, and Cancelled.
          Currently, the contract is in <strong>{contractData.status}</strong> state.
        </p>

        <p className="text-gray-800 mt-4">
          This agreement is stored on the blockchain and digitally signed by both parties for full
          transparency and authenticity.
        </p>

        <div className="mt-8 text-center">
          <button
            onClick={downloadPDF}
            className="bg-green-600 hover:bg-green-700 text-white px-6 py-2 rounded-lg shadow-md transition"
          >
            Download Agreement (PDF)
          </button>
        </div>
      </div>
    </div>
  );
};

export default ContractAgreementPage;
