import React, { useEffect, useState } from "react";
import { useParams, useLocation, Link } from "react-router-dom";
import { ethers } from "ethers";
import { CONTRACT_ABI, CONTRACT_ADDRESS } from "../../contractconfig";
import jsPDF from "jspdf";
import FarmerNavbar from '../../components/FarmerNavbar';
import BuyerNavbar from '../../components/BuyerNavbar';

const ContractAgreementPage = () => {
  const { id } = useParams();
  const location = useLocation();
  const isBuyer = location.pathname.startsWith('/buyer');
  const [contractData, setContractData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  useEffect(() => {
    const loadContract = async () => {
      try {
        if (!window.ethereum) throw new Error("MetaMask not detected");
        const provider = new ethers.BrowserProvider(window.ethereum);
        const contract = new ethers.Contract(CONTRACT_ADDRESS, CONTRACT_ABI, provider);
        const data = await contract.getContract(Number(id));
        setContractData({
          id: Number(id),
          orderId: data.orderId,
          cropName: data.cropName,
          price: ethers.formatUnits(data.price.toString(), "wei"),
          acres: data.acres.toString(),
          deliveryDate: data.deliveryDate,
          status: ["Created", "Accepted", "In Progress", "Completed", "Cancelled"][Number(data.status)],
          farmerWallet: data.farmerWallet,
          buyerWallet: data.buyerWallet,
        });
      } catch (err) {
        console.error(err);
        setError("Failed to load contract details");
      } finally {
        setLoading(false);
      }
    };
    loadContract();
  }, [id]);

  const downloadPDF = () => {
    if (!contractData) return;
    const doc = new jsPDF();
    doc.setFillColor(34, 139, 34);
    doc.rect(0, 0, 210, 25, "F");
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(16);
    doc.text(" FarmaFriend Smart Farming Agreement", 14, 16);
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(12);
    let y = 35;
    doc.setFont("helvetica", "bold");
    doc.text("Contract Overview", 14, y);
    doc.setFont("helvetica", "normal");
    y += 8;
    const details = [
      `Contract ID: ${contractData.orderId}`,
      `Status: ${contractData.status}`,
      "",
      `Farmer Wallet: ${contractData.farmerWallet}`,
      `Buyer Wallet: ${contractData.buyerWallet}`,
      "",
      `Crop: ${contractData.cropName}`,
      `Land Area: ${contractData.acres} acres`,
      `Delivery Date: ${contractData.deliveryDate}`,
      `Agreed Price in Rupees:  ${contractData.price}`,
    ];
    details.forEach(line => { doc.text(line, 20, y); y += 8; });
    doc.setDrawColor(100, 100, 100);
    doc.line(14, y, 196, y);
    y += 10;
    doc.setFont("helvetica", "bold");
    doc.text("Responsibilities", 14, y);
    y += 8;
    doc.setFont("helvetica", "normal");
    const duties = [
      "- Farmer ensures proper cultivation, harvest, and timely delivery.",
      "- Buyer agrees to make payment upon satisfactory delivery.",
      "- Both parties must maintain communication for any delays or issues.",
    ];
    duties.forEach(line => { doc.text(line, 20, y); y += 8; });
    y += 5;
    doc.line(14, y, 196, y);
    y += 10;
    doc.setFont("helvetica", "bold");
    doc.text("Current Blockchain Status:", 14, y);
    doc.setFont("helvetica", "normal");
    y += 8;
    doc.text(`This contract is currently marked as "${contractData.status}".`, 20, y);
    y += 10;
    doc.setFont("helvetica", "bold");
    doc.text("Blockchain Record", 14, y);
    doc.setFont("helvetica", "normal");
    y += 8;
    doc.text("This agreement is permanently recorded on the blockchain network, ensuring transparency,", 20, y);
    y += 6;
    doc.text("immutability, and security. No modifications can be made after finalization by both parties.", 20, y);
    y += 15;
    doc.setFont("helvetica", "bold");
    doc.text("Digitally Signed By:", 14, y);
    y += 8;
    doc.setFont("helvetica", "normal");
    doc.text(`Farmer: ${contractData.farmerWallet}`, 20, y);
    y += 8;
    doc.text(`Buyer: ${contractData.buyerWallet}`, 20, y);
    y += 20;
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text("Generated by FarmaFriend • Smart Contract Agreement", 14, y);
    doc.save(`FarmaFriend_Agreement_${contractData.orderId}.pdf`);
  };

  const basePath = isBuyer ? '/buyer' : '/farmer';

  if (loading) return (
    <div className="min-h-screen bg-gray-50">
      {isBuyer ? <BuyerNavbar /> : <FarmerNavbar />}
      <div className="flex flex-col items-center py-20">
        <div className="w-10 h-10 border-4 border-green-200 border-t-green-600 rounded-full animate-spin mb-4"></div>
        <p className="text-gray-500 text-sm">Loading agreement from blockchain...</p>
      </div>
    </div>
  );

  if (error) return (
    <div className="min-h-screen bg-gray-50">
      {isBuyer ? <BuyerNavbar /> : <FarmerNavbar />}
      <div className="text-center py-20">
        <div className="text-5xl mb-4">⚠️</div>
        <h3 className="text-xl font-semibold text-red-600 mb-2">Error</h3>
        <p className="text-gray-400 text-sm">{error}</p>
      </div>
    </div>
  );

  if (!contractData) return null;

  return (
    <div className="min-h-screen bg-gray-50">
      {isBuyer ? <BuyerNavbar /> : <FarmerNavbar />}

      {/* Breadcrumb */}
      <div className="bg-white border-b border-gray-100 py-3 px-6">
        <div className="max-w-4xl mx-auto flex items-center gap-2 text-sm">
          <Link to={`${basePath}/contract/${id}`} className="text-green-600 hover:text-green-700 font-medium flex items-center gap-1">
            <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" />
            </svg>
            Contract Details
          </Link>
          <span className="text-gray-300">/</span>
          <span className="text-gray-500">Agreement</span>
        </div>
      </div>

      <div className="max-w-4xl mx-auto px-4 py-8">
        {/* Agreement Document Card */}
        <div className="bg-white rounded-2xl shadow-sm border border-gray-100 overflow-hidden">
          {/* Document Header */}
          <div className="bg-gradient-to-r from-green-700 to-green-600 px-8 py-6 text-center">
            <div className="w-14 h-14 bg-white/20 rounded-2xl flex items-center justify-center mx-auto mb-3">
              <span className="text-3xl">📜</span>
            </div>
            <h1 className="text-2xl font-bold text-white">Smart Farming Agreement</h1>
            <p className="text-green-100 text-sm mt-1">Blockchain-verified contract between farmer and buyer</p>
          </div>

          {/* Document Body */}
          <div className="px-8 py-6">
            {/* Meta Info */}
            <div className="flex flex-wrap gap-4 mb-6 pb-6 border-b border-gray-100">
              <div className="bg-gray-50 rounded-xl px-4 py-2.5">
                <p className="text-xs text-gray-500">Date</p>
                <p className="text-sm font-semibold text-gray-700">{new Date().toLocaleDateString()}</p>
              </div>
              <div className="bg-gray-50 rounded-xl px-4 py-2.5">
                <p className="text-xs text-gray-500">Agreement ID</p>
                <p className="text-sm font-semibold text-gray-700">{contractData.orderId}</p>
              </div>
              <div className="bg-gray-50 rounded-xl px-4 py-2.5">
                <p className="text-xs text-gray-500">Blockchain ID</p>
                <p className="text-sm font-semibold text-gray-700">#{contractData.id}</p>
              </div>
              <div className={`rounded-xl px-4 py-2.5 ${contractData.status === 'Completed' ? 'bg-emerald-50' :
                contractData.status === 'Cancelled' ? 'bg-red-50' : 'bg-blue-50'
                }`}>
                <p className="text-xs text-gray-500">Status</p>
                <p className={`text-sm font-semibold ${contractData.status === 'Completed' ? 'text-emerald-700' :
                  contractData.status === 'Cancelled' ? 'text-red-700' : 'text-blue-700'
                  }`}>{contractData.status}</p>
              </div>
            </div>

            {/* Parties */}
            <div className="mb-6">
              <h3 className="text-sm font-semibold text-gray-500 uppercase tracking-wider mb-3">Parties Involved</h3>
              <p className="text-gray-700 leading-relaxed text-sm">
                This agreement is made between <span className="font-semibold text-green-700">Farmer</span> (<code className="text-xs bg-gray-100 px-2 py-0.5 rounded">{contractData.farmerWallet}</code>) and{" "}
                <span className="font-semibold text-blue-700">Buyer</span> (<code className="text-xs bg-gray-100 px-2 py-0.5 rounded">{contractData.buyerWallet}</code>) under the FarmaFriend Smart Farming Platform.
              </p>
            </div>

            {/* Terms */}
            <div className="mb-6">
              <h3 className="text-sm font-semibold text-gray-500 uppercase tracking-wider mb-3">Contract Terms</h3>
              <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
                <div className="bg-green-50 rounded-xl px-4 py-3 text-center">
                  <p className="text-xs text-gray-500 mb-1">Crop</p>
                  <p className="text-sm font-bold text-green-800">{contractData.cropName}</p>
                </div>
                <div className="bg-orange-50 rounded-xl px-4 py-3 text-center">
                  <p className="text-xs text-gray-500 mb-1">Land Area</p>
                  <p className="text-sm font-bold text-orange-700">{contractData.acres} acres</p>
                </div>
                <div className="bg-blue-50 rounded-xl px-4 py-3 text-center">
                  <p className="text-xs text-gray-500 mb-1">Delivery</p>
                  <p className="text-sm font-bold text-blue-700">{contractData.deliveryDate}</p>
                </div>
                <div className="bg-purple-50 rounded-xl px-4 py-3 text-center">
                  <p className="text-xs text-gray-500 mb-1">Agreed Price</p>
                  <p className="text-sm font-bold text-purple-700">₹{contractData.price}</p>
                </div>
              </div>
            </div>

            {/* Responsibilities */}
            <div className="mb-6">
              <h3 className="text-sm font-semibold text-gray-500 uppercase tracking-wider mb-3">Responsibilities</h3>
              <div className="space-y-2">
                {[
                  { icon: '🌾', text: 'Farmer ensures proper cultivation, harvest, and timely delivery.' },
                  { icon: '💰', text: 'Buyer agrees to make payment upon satisfactory delivery.' },
                  { icon: '📞', text: 'Both parties must maintain communication for any delays or issues.' },
                ].map((item, idx) => (
                  <div key={idx} className="flex items-start gap-3 p-3 bg-gray-50 rounded-xl">
                    <span className="text-lg">{item.icon}</span>
                    <p className="text-sm text-gray-700">{item.text}</p>
                  </div>
                ))}
              </div>
            </div>

            {/* Status Info */}
            <div className="mb-6 p-4 bg-green-50 rounded-xl border border-green-100">
              <div className="flex items-start gap-3">
                <span className="text-lg">⛓️</span>
                <div>
                  <p className="text-sm font-semibold text-green-800 mb-1">Blockchain Record</p>
                  <p className="text-sm text-green-700 leading-relaxed">
                    This agreement is permanently recorded on the blockchain network, ensuring transparency, immutability, and security.
                    Currently marked as <span className="font-bold">"{contractData.status}"</span>.
                  </p>
                </div>
              </div>
            </div>

            {/* Digital Signatures */}
            <div className="mb-6">
              <h3 className="text-sm font-semibold text-gray-500 uppercase tracking-wider mb-3">Digital Signatures</h3>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                <div className="p-4 border border-gray-200 rounded-xl">
                  <p className="text-xs text-gray-500 mb-1">Farmer Signature</p>
                  <p className="text-xs font-mono text-gray-600 break-all">{contractData.farmerWallet}</p>
                  <div className="mt-2 flex items-center gap-1 text-xs text-green-600">
                    <svg xmlns="http://www.w3.org/2000/svg" className="h-3.5 w-3.5" viewBox="0 0 20 20" fill="currentColor">
                      <path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd" />
                    </svg>
                    Verified on-chain
                  </div>
                </div>
                <div className="p-4 border border-gray-200 rounded-xl">
                  <p className="text-xs text-gray-500 mb-1">Buyer Signature</p>
                  <p className="text-xs font-mono text-gray-600 break-all">{contractData.buyerWallet}</p>
                  <div className="mt-2 flex items-center gap-1 text-xs text-green-600">
                    <svg xmlns="http://www.w3.org/2000/svg" className="h-3.5 w-3.5" viewBox="0 0 20 20" fill="currentColor">
                      <path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd" />
                    </svg>
                    Verified on-chain
                  </div>
                </div>
              </div>
            </div>
          </div>

          {/* Download Footer */}
          <div className="px-8 py-5 bg-gray-50 border-t border-gray-100 flex items-center justify-between">
            <p className="text-xs text-gray-400">Generated by FarmaFriend • Smart Contract Agreement</p>
            <button
              onClick={downloadPDF}
              className="bg-green-600 text-white px-6 py-2.5 rounded-xl font-medium hover:bg-green-700 transition flex items-center gap-2 shadow-sm"
            >
              <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
              </svg>
              Download PDF
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};

export default ContractAgreementPage;
